
version: 2

models:
    - name: desjpposts
      description: "data extractor services job posts table"
      columns:
          - name: job_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: odsalljobs
      description: "A starter dbt model"
      columns:
          - name: job_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: mergedodsdes
      description: "merged ods and data extractor services tables"
      columns:
        - name: job_id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
