version: 2

sources:
  - name: ods_job_posts
    database: "DEV_DB"
    schema: ODS
    tables:
      - name: ODS_ALLJOBS_ENRICHED
  - name: des_job_posts
    database: "DEV_DB"
    schema: EXTRACTOR_SERVICES
    tables:
      - name: ALLJOBS_JOB_POSTS