{{ config(materialized='raw_sql', schema='ODS')}}

/*
# ODS Indeed IL Status Updates Loader

This model loads status files that were generated by Indeed extractor or status checker from GCS to ODS database.
*/

{% set source_table_var= 'ods_indeed_il_jps_status' %}

{{ load_jps_to_ods('indeed/il',source_table_var) }}



