{{ config(materialized='raw_sql',schema='ods')}}

/*
# ODS Indeed Extractor Status Loader

This model loads status files that were generated by Indeed extractor from GCS to ODS database.
Expects site variable.
site variable can be one of ['IL', 'UAE', 'US']
*/

{% set dates_arr=get_date_macro() %}

--{% set source_name='ODS_INDEED_' + var("site")|string|upper + '_STATUS' %}
{% set source_table= 'ODS_INDEED_' + var("site")|string|upper + '_STATUS_TEST1' %}

copy into {{ref(source_table)}}
from(
    select
        parse_json($1):job_id as job_id,
        parse_json($1) as json_data,
        parse_json($1):source as source,
        metadata$filename as file_name,
        metadata$file_row_number as row_number,
        current_timestamp() as load_date
    from
        {{var('bucket_datasets_stage')}}/{{'job_boards/indeed/'}}{{var('site')|string|lower}}{{'/status'}}/{{dates_arr[0]}}/{{dates_arr[1]}}/{{dates_arr[2]}}/(
           file_format => {{var('json_ff')}} ,pattern=>'.*20230108.*json'
        )
 );