{{ config(materialized='raw_sql',schema='ods')}}

/*
# ODS Indeed Extractor Status Loader

This model loads status files that were generated by Indeed extractor from GCS to ODS database.
Expects site variable.
site variable can be one of ['IL', 'UAE', 'US']
*/

{% set dates_arr=get_date_macro() %}

{% set source_name='ods_indeed_status' %}
{% set source_table= 'ods_indeed_' + var("site")|string|lower + '_status_test3' %}

copy into {{source(source_name, source_table)}}
from(
    select
        parse_json($1):job_id as job_id,
        parse_json($1) as json_data,
        parse_json($1):source as source,
        metadata$filename as file_name,
        metadata$file_row_number as row_number,
        current_timestamp() as load_date
    from
        {{var('bucket_datasets_stage')}}/{{'job_boards/indeed/'}}{{var('site')|string|lower}}{{'/status'}}/2023/01/16/(
           file_format => {{var('json_ff')}} ,pattern=>'.*json'
        )
 )
 FORCE = TRUE
 ;