
version: 2

models:
    - name: ods_indeed_job_post_status
      description: "data extractor services job posts status table"
      columns:
          - name: job_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: ods_indeed_status_stg
      description: "Staging step before loading data to DWH of status"
      columns:
        - name: job_id
          tests:
            - unique
            - not_null

